"""Seed data for database initialization."""

SERVICE_CATEGORIES = [
    {
        "name": "Facials & Skin Treatments",
        "description": "Rejuvenating facial treatments tailored to your skin type",
        "sort_order": 1,
    },
    {
        "name": "Hair & Scalp Treatments",
        "description": "Nourishing treatments to restore shine and scalp health",
        "sort_order": 2,
    },
    {
        "name": "Body Treatments",
        "description": "Full-body relaxation and skin renewal therapies",
        "sort_order": 3,
    },
    {
        "name": "Nail Services",
        "description": "Professional nail care, polish, and pedicure treatments",
        "sort_order": 4,
    },
    {
        "name": "Waxing & Threading",
        "description": "Precise hair removal for smooth, long-lasting results",
        "sort_order": 5,
    },
]

SERVICES = [
    {
        "name": "Signature Glow Facial",
        "category_name": "Facials & Skin Treatments",
        "description": "Our signature 60-minute facial combines deep cleansing, exfoliation, steam, and a customised mask to leave your skin luminous and refreshed.",
        "base_price": 85,
        "duration_mins": 60,
        "instructions": "Arrive with clean skin, no makeup. Avoid retinol 48h before treatment.",
        "sort_order": 1,
    },
    {
        "name": "Deep Pore Cleansing",
        "category_name": "Facials & Skin Treatments",
        "description": "Targeted treatment to unclog pores, remove blackheads, and rebalance oily or congested skin.",
        "base_price": 65,
        "duration_mins": 45,
        "instructions": "Ideal every 4–6 weeks. Avoid active breakout areas 24h before.",
        "sort_order": 2,
    },
    {
        "name": "Anti-Aging Lift Facial",
        "category_name": "Facials & Skin Treatments",
        "description": "Intensive collagen-boosting facial with peptide serums, LED therapy, and firming massage techniques to visibly lift and plump.",
        "base_price": 120,
        "duration_mins": 75,
        "instructions": "Patch test required for sensitive skin. SPF mandatory post-treatment.",
        "sort_order": 3,
    },
    {
        "name": "Microdermabrasion",
        "category_name": "Facials & Skin Treatments",
        "description": "Crystal-free diamond tip resurfacing that buffs away dead skin cells, reducing fine lines, acne scars, and uneven texture.",
        "base_price": 95,
        "duration_mins": 60,
        "instructions": "Do not use retinol 1 week before. Stay out of direct sun for 48h after.",
        "sort_order": 4,
    },
    {
        "name": "Chemical Peel (Lactic)",
        "category_name": "Facials & Skin Treatments",
        "description": "Gentle lactic acid peel to brighten, hydrate, and smooth the skin surface — perfect for first-time peel clients.",
        "base_price": 110,
        "duration_mins": 45,
        "instructions": "Avoid active sunburn. No gym or sweating for 24h post-peel.",
        "sort_order": 5,
    },
    {
        "name": "Scalp Revival Treatment",
        "category_name": "Hair & Scalp Treatments",
        "description": "Therapeutic scalp massage with detox exfoliation and a targeted serum infusion to address dryness, flaking, and hair thinning.",
        "base_price": 55,
        "duration_mins": 45,
        "instructions": "Come with unwashed hair for best absorption of treatment oils.",
        "sort_order": 1,
    },
    {
        "name": "Keratin Bond Treatment",
        "category_name": "Hair & Scalp Treatments",
        "description": "Intensive protein reconstruction treatment that seals the hair cuticle, eliminates frizz, and restores elasticity for up to 8 weeks.",
        "base_price": 145,
        "duration_mins": 90,
        "instructions": "Do not wash hair for 72h after. Avoid salt water and chlorine for 2 weeks.",
        "sort_order": 2,
    },
    {
        "name": "Deep Conditioning Mask",
        "category_name": "Hair & Scalp Treatments",
        "description": "Warm oil infusion followed by a 30-minute deep conditioning mask customised to your hair type — dry, damaged, or colour-treated.",
        "base_price": 45,
        "duration_mins": 30,
        "instructions": "Can be combined with any other hair service.",
        "sort_order": 3,
    },
    {
        "name": "Hot Stone Back Massage",
        "category_name": "Body Treatments",
        "description": "Heated basalt stones glide over the back, shoulders, and neck to melt tension, improve circulation, and deeply relax tired muscles.",
        "base_price": 95,
        "duration_mins": 60,
        "instructions": "Drink plenty of water before and after. Avoid alcohol 4h prior.",
        "sort_order": 1,
    },
    {
        "name": "Full Body Exfoliation",
        "category_name": "Body Treatments",
        "description": "Head-to-toe sugar scrub followed by a hydrating lotion application — leaves skin silky smooth and ready to absorb moisture.",
        "base_price": 85,
        "duration_mins": 60,
        "instructions": "Shower before your appointment. Best results when skin is dry.",
        "sort_order": 2,
    },
    {
        "name": "Aromatherapy Detox Wrap",
        "category_name": "Body Treatments",
        "description": "Detoxifying clay body mask wrapped to draw out impurities, followed by a warm rinse and application of nourishing botanical oils.",
        "base_price": 110,
        "duration_mins": 75,
        "instructions": "Avoid eating a heavy meal 2h prior. Wear or bring loose, comfortable clothing.",
        "sort_order": 3,
    },
    {
        "name": "Classic Gel Manicure",
        "category_name": "Nail Services",
        "description": "Shape, buff, and cuticle care followed by a long-lasting gel polish application. Chip-free for up to 3 weeks.",
        "base_price": 38,
        "duration_mins": 45,
        "instructions": "Remove previous gel polish before your appointment if possible.",
        "sort_order": 1,
    },
    {
        "name": "Luxury Spa Pedicure",
        "category_name": "Nail Services",
        "description": "Foot soak, callus removal, extended massage, and a gel polish finish — a full hour of pure pedicure indulgence.",
        "base_price": 68,
        "duration_mins": 60,
        "instructions": "Shave legs at least 24h before to avoid irritation. Bring open-toe shoes.",
        "sort_order": 2,
    },
    {
        "name": "Eyebrow Threading & Tint",
        "category_name": "Waxing & Threading",
        "description": "Precise cotton thread technique to shape and define brows, followed by a custom tint to add depth and colour.",
        "base_price": 28,
        "duration_mins": 20,
        "instructions": "Patch test required 24h before tint. Avoid threading during active skin irritation.",
        "sort_order": 1,
    },
    {
        "name": "Full Leg Wax",
        "category_name": "Waxing & Threading",
        "description": "Smooth, long-lasting hair removal from the knee to hip using low-temperature strip wax suited for all skin tones.",
        "base_price": 65,
        "duration_mins": 45,
        "instructions": "Hair must be at least 0.5 cm. Exfoliate 24h before. Avoid moisturiser on the day.",
        "sort_order": 2,
    },
]

PRODUCTS = [
    {
        "name": "Vitamin C Brightening Serum",
        "category_name": "Skincare",
        "description": "15% stabilised Vitamin C with ferulic acid and niacinamide. Fades dark spots, boosts collagen, and delivers a luminous glow with daily use.",
        "sku": "GBM-SK-001",
        "price": 48,
        "cost_price": 18,
        "stock_quantity": 45,
        "low_stock_threshold": 10,
        "image_key": "vitamin-c-serum",
    },
    {
        "name": "Hyaluronic Acid Moisturiser",
        "category_name": "Skincare",
        "description": "Lightweight gel-cream with triple-molecular-weight hyaluronic acid that delivers 72-hour moisture lock without feeling heavy.",
        "sku": "GBM-SK-002",
        "price": 42,
        "cost_price": 15,
        "stock_quantity": 60,
        "low_stock_threshold": 12,
        "image_key": "hyaluronic-moisturizer",
    },
    {
        "name": "Gentle Foaming Cleanser",
        "category_name": "Skincare",
        "description": "pH-balanced, sulphate-free foaming cleanser that removes makeup and impurities without stripping the skin's natural barrier.",
        "sku": "GBM-SK-003",
        "price": 28,
        "cost_price": 9,
        "stock_quantity": 80,
        "low_stock_threshold": 15,
        "image_key": "foaming-cleanser",
    },
    {
        "name": "Rose Hip Facial Oil",
        "category_name": "Skincare",
        "description": "Cold-pressed, 100% pure rosehip seed oil rich in Vitamin A and essential fatty acids. Repairs, firms, and visibly reduces scarring.",
        "sku": "GBM-SK-004",
        "price": 52,
        "cost_price": 20,
        "stock_quantity": 30,
        "low_stock_threshold": 8,
        "image_key": "rosehip-facial-oil",
    },
    {
        "name": "SPF 50 Daily Sunscreen",
        "category_name": "Skincare",
        "description": "Broad-spectrum UVA/UVB mineral sunscreen with zinc oxide. Invisible finish, water-resistant, and reef-safe. Wear every day.",
        "sku": "GBM-SK-005",
        "price": 35,
        "cost_price": 12,
        "stock_quantity": 55,
        "low_stock_threshold": 12,
        "image_key": "daily-sunscreen",
    },
    {
        "name": "Retinol Night Renewal Cream",
        "category_name": "Skincare",
        "description": "Encapsulated 0.3% retinol with squalane and ceramides for overnight cell turnover — visible smoothing with minimal irritation.",
        "sku": "GBM-SK-006",
        "price": 58,
        "cost_price": 22,
        "stock_quantity": 35,
        "low_stock_threshold": 8,
        "image_key": "retinol-night-cream",
    },
    {
        "name": "Exfoliating Sugar Scrub",
        "category_name": "Skincare",
        "description": "Fine-grain cane sugar scrub blended with jojoba beads and mandelic acid. Buffs away dead cells to reveal brighter, smoother skin.",
        "sku": "GBM-SK-007",
        "price": 32,
        "cost_price": 10,
        "stock_quantity": 40,
        "low_stock_threshold": 10,
        "image_key": "sugar-scrub",
    },
    {
        "name": "Eye Revive Cream",
        "category_name": "Skincare",
        "description": "Caffeine + peptide formula that deflates puffiness, brightens dark circles, and firms the delicate eye contour in 4 weeks.",
        "sku": "GBM-SK-008",
        "price": 45,
        "cost_price": 16,
        "stock_quantity": 28,
        "low_stock_threshold": 8,
        "image_key": "eye-revive-cream",
    },
    {
        "name": "Keratin Repair Shampoo",
        "category_name": "Haircare",
        "description": "Sulphate-free shampoo infused with hydrolysed keratin proteins and argan oil to reconstruct damaged bonds and restore natural lustre.",
        "sku": "GBM-HC-001",
        "price": 28,
        "cost_price": 9,
        "stock_quantity": 50,
        "low_stock_threshold": 10,
        "image_key": "keratin-shampoo",
    },
    {
        "name": "Deep Moisture Hair Mask",
        "category_name": "Haircare",
        "description": "Weekly intensive mask with shea butter, coconut oil, and silk amino acids. Restores elasticity and eliminates frizz for 7 days.",
        "sku": "GBM-HC-002",
        "price": 36,
        "cost_price": 12,
        "stock_quantity": 38,
        "low_stock_threshold": 8,
        "image_key": "hair-mask",
    },
    {
        "name": "Scalp Balance Tonic",
        "category_name": "Haircare",
        "description": "Lightweight daily spray tonic with salicylic acid, zinc pyrithione, and peppermint. Regulates oil, calms irritation, and promotes hair growth.",
        "sku": "GBM-HC-003",
        "price": 30,
        "cost_price": 10,
        "stock_quantity": 42,
        "low_stock_threshold": 10,
        "image_key": "scalp-tonic",
    },
    {
        "name": "Lavender Body Lotion",
        "category_name": "Body Care",
        "description": "Velvety body lotion with shea butter, vitamin E, and therapeutic lavender essential oil. Absorbs fast, no greasy residue.",
        "sku": "GBM-BC-001",
        "price": 26,
        "cost_price": 8,
        "stock_quantity": 65,
        "low_stock_threshold": 15,
        "image_key": "body-lotion",
    },
    {
        "name": "Detoxifying Body Scrub",
        "category_name": "Body Care",
        "description": "Activated charcoal and coffee-ground exfoliant that draws out toxins, smooths cellulite, and leaves the skin perfectly prepped for moisturiser.",
        "sku": "GBM-BC-002",
        "price": 34,
        "cost_price": 11,
        "stock_quantity": 48,
        "low_stock_threshold": 10,
        "image_key": "body-scrub",
    },
    {
        "name": "Jade Facial Roller",
        "category_name": "Tools & Accessories",
        "description": "Genuine nephrite jade double-ended roller. Use daily to depuff, improve product absorption, and promote lymphatic drainage.",
        "sku": "GBM-TA-001",
        "price": 28,
        "cost_price": 8,
        "stock_quantity": 25,
        "low_stock_threshold": 5,
        "image_key": "jade-roller",
    },
    {
        "name": "Gua Sha Stone Set",
        "category_name": "Tools & Accessories",
        "description": "Set of two rose quartz gua sha stones — one for the face and one for the neck — with a velvet carry pouch and instructional guide.",
        "sku": "GBM-TA-002",
        "price": 32,
        "cost_price": 10,
        "stock_quantity": 20,
        "low_stock_threshold": 5,
        "image_key": "gua-sha",
    },
]

CONSULTATION_TEMPLATES = [
    {
        "name": "New Client Intake Form",
        "description": "Comprehensive first-visit form covering health history, skin goals, and preferences.",
        "fields": [
            {"id": "f1", "label": "Date of birth", "type": "date", "required": True},
            {
                "id": "f2",
                "label": "Primary skin concern",
                "type": "select",
                "required": True,
                "options": [
                    "Acne & breakouts",
                    "Ageing & fine lines",
                    "Dryness & dehydration",
                    "Hyperpigmentation",
                    "Redness & sensitivity",
                    "Uneven texture",
                    "Other",
                ],
            },
            {
                "id": "f3",
                "label": "Current skincare routine",
                "type": "textarea",
                "required": False,
                "placeholder": "Describe your morning and evening routine",
            },
            {
                "id": "f4",
                "label": "Do you have any known allergies?",
                "type": "radio",
                "required": True,
                "options": ["Yes", "No"],
            },
            {"id": "f5", "label": "If yes, please list your allergies", "type": "textarea", "required": False},
            {
                "id": "f6",
                "label": "Are you currently pregnant or breastfeeding?",
                "type": "radio",
                "required": True,
                "options": ["Yes", "No", "Prefer not to say"],
            },
            {
                "id": "f7",
                "label": "How did you hear about us?",
                "type": "select",
                "required": False,
                "options": ["Instagram", "Google", "Friend referral", "Walk-in", "Other"],
            },
        ],
    },
]

TREATMENT_PLAN_TEMPLATES = [
    {
        "name": "30-Day Glow Skin Reset",
        "description": "A one-month intensive designed to deeply cleanse, resurface, and brighten dull or congested skin. Combines professional treatments with a structured home-care routine.",
        "duration_days": 30,
        "steps": [
            {
                "day": 1,
                "title": "Initial Skin Assessment & Deep Cleanse",
                "description": "Perform a full skin analysis, photograph baseline condition, and complete a 60-minute deep-cleansing facial to remove congestion and prepare the skin for active treatment.",
                "recommended_products": ["Gentle Foaming Cleanser", "Hyaluronic Acid Moisturiser"],
            },
            {
                "day": 3,
                "title": "Home-Care Protocol Introduction",
                "description": "Walk the client through their prescribed home-care regimen — morning Vitamin C serum, SPF 50+, and evening double-cleanse with hyaluronic moisturiser. Set realistic expectations for the first week.",
                "recommended_products": [
                    "Vitamin C Brightening Serum",
                    "Hyaluronic Acid Moisturiser",
                    "Gentle Foaming Cleanser",
                ],
            },
        ],
    },
]


def BUSINESS_SETTINGS(admin_id: str) -> list[dict]:
    """Generate business settings with admin user ID."""
    return [
        {
            "key": "business_info",
            "value": {
                "name": "Glow By Miral",
                "tagline": "Your beauty, our passion",
                "email": "hello@glowbymiral.com",
                "phone": "+1 (555) 100-2000",
                "address": "42 Blossom Lane, Suite 3, Beverly Hills, CA 90210",
                "website": "https://glowbymiral.com",
                "timezone": "America/Los_Angeles",
                "currency": "USD",
            },
            "updated_by": admin_id,
        },
        {
            "key": "working_hours",
            "value": {
                "0": {"open": False, "start": "09:00", "end": "18:00"},
                "1": {"open": True, "start": "09:00", "end": "18:00"},
                "2": {"open": True, "start": "09:00", "end": "18:00"},
                "3": {"open": True, "start": "09:00", "end": "20:00"},
                "4": {"open": True, "start": "09:00", "end": "20:00"},
                "5": {"open": True, "start": "09:00", "end": "18:00"},
                "6": {"open": True, "start": "10:00", "end": "16:00"},
            },
            "updated_by": admin_id,
        },
        {
            "key": "notification_settings",
            "value": {
                "appointment_reminder_hours": 24,
                "send_confirmation_email": True,
                "send_reminder_sms": False,
                "notify_admin_on_booking": True,
            },
            "updated_by": admin_id,
        },
        {
            "key": "booking_settings",
            "value": {
                "min_advance_hours": 2,
                "max_advance_days": 60,
                "allow_customer_cancel_hours": 24,
                "slot_interval_mins": 15,
            },
            "updated_by": admin_id,
        },
    ]
